### ISSUE TITLE
Panic when `sync_with_custom_puppets` is enabled

### ISSUE THREAD

**Issue by JacobSnyder** [mautrix/imessage#198]
I noticed my other mautrix bridges have `sync_with_custom_puppets`, so I figured I'd try enabling it (I don't know what it does, but sure!).  I saw that `ephemeral_events` should be disabled, so I disabled that too. I then launch `mautrix-imessage` and get a panic pretty quickly:

```
2024-03-05T21:20:16-08:00 INF Successfully automatically enabled custom puppet module=User/@jacob:mydomain.com
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x20 pc=0x1045bbc48]

goroutine 7 [running]:
maunium.net/go/mautrix.(*Client).SyncWithContext(0x140001302c0, {0x104cf3518, 0x105188920})
        /Users/ci/go/pkg/mod/maunium.net/go/mautrix@v0.16.0/client.go:176 +0x78
maunium.net/go/mautrix.(*Client).Sync(...)
        /Users/ci/go/pkg/mod/maunium.net/go/mautrix@v0.16.0/client.go:168
main.(*User).startSyncing.func1()
        /Users/ci/builds/YUMeaPfZ/0/mautrix/imessage/custompuppet.go:159 +0x3c
created by main.(*User).startSyncing in goroutine 1
        /Users/ci/builds/YUMeaPfZ/0/mautrix/imessage/custompuppet.go:158 +0x178
```

Things I tried:

- Enabling `ephemeral_events`
- Clearing my database
- Trying a different platform (I was using `bluebubbles`, tried `mac`)

I'm running `mautrix-imessage v0.1.0+dev.ea7aebde` on Synapse v1.101.0.

I'll attach my full log and config:

- [config.yaml.txt](https://github.com/mautrix/imessage/files/14505023/config.yaml.txt)
- [log.txt](https://github.com/mautrix/imessage/files/14505025/log.txt)

PS: This is super low-pri for me, more of a curiosity more than anything but I thought ya'll might want to know. Thanks for all the hard work! Cheers!

**Comment by JacobSnyder** [comment]
Whoops, I leaked a secret in my config - I went ahead and rolled it!
