### ISSUE TITLE
Mac-NoSIP Crashing - Runtime Error invalid memory address

### ISSUE THREAD

**Issue by shatt-sda** [mautrix/imessage#58]
When running matrix-imessage on a Mac with SIP disabled, I keep getting this error and I cannot figure out why. Any help you can provide would be greatly appreciated, let me know what other information would be helpful for debugging! 

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x451123b]

goroutine 48 [running]:
os.(*ProcessState).exited(...)
	/usr/local/Cellar/go/1.18/libexec/src/os/exec_posix.go:83
os.(*ProcessState).Exited(...)
	/usr/local/Cellar/go/1.18/libexec/src/os/exec.go:155
go.mau.fi/mautrix-imessage/imessage/mac-nosip.(*MacNoSIPConnector).Start.func1()
	/Users/tulir/builds/i2hvwHJ9/0/mautrix/imessage/imessage/mac-nosip/nosip.go:89 +0x3b
created by go.mau.fi/mautrix-imessage/imessage/mac-nosip.(*MacNoSIPConnector).Start
	/Users/tulir/builds/i2hvwHJ9/0/mautrix/imessage/imessage/mac-nosip/nosip.go:87 +0x274

**Comment by shatt-sda** [comment]
Running on an Intel-based MacBook Pro running macOS 12.3.1 Monterey

**Comment by shatt-sda** [comment]
I did see the other issue here with the same message which ended up being AMFI, but I have gone through the steps in the documentation to disable SIP and AMFI 4 times and still no luck. Thanks!

**Comment by misraaks** [comment]
Are you using OpenCore Patcher to run Monterey on an older Mac? I ran into this and needed to mount the EFI partition and add the AMFI boot arg to EFI/OC/config.plist

**Comment by ajkessel** [comment]
I had this issue as well and my solution is documented [here](https://docs.mau.fi/bridges/go/imessage/mac-nosip/setup.html#disabling-sip-and-amfi)
